### ISSUE TITLE
rt #85418: fails 98pod-coverage.t on Perl 5.18

### ISSUE THREAD

**Issue by rsrchboy** [p5-shorten/www-shorten#1]
I'm seeing the same set of test fails as described in [rt#85418](https://rt.cpan.org/Ticket/Display.html?id=85418), and I suspect at least a couple of the 499 fails listed at cpantesters are as well :)

/cc @kentfredric

**Comment by rsrchboy** [comment]
...now at 706 cpantesters test fails, and counting.

**Comment by davorg** [comment]
This bug is being tracked on RT - https://rt.cpan.org/Public/Bug/Display.html?id=85418
