### ISSUE TITLE
Perl Version Support

### ISSUE THREAD

**Issue by genio** [p5-shorten/www-shorten#11]
Moving forward to only supporting Perl >= 5.8.1 would relieve some of the maintenance annoyance.

Any thoughts?

**Comment by davorg** [comment]
In my opinion. anyone using a Perl < 5.8.8 doesn't deserve support :-)

**Comment by oliwer** [comment]
I would also vote for perl 5.8.8, which documentation at least is still visible on perldoc.perl.org.

**Comment by genio** [comment]
With 3.093 support is for >= 5.8.1.  Hopefully >= 5.10.1 isn't far off (glares at RHEL 5)
