### ISSUE TITLE
tinyurl uses "https" now.

### ISSUE THREAD

**Issue by lembark** [p5-shorten/www-shorten#15]
WWW/Shorten/TinyURL.pm needs "https" in a few places:

--- TinyURL.pm~ 2016-03-25 16:16:15.000000000 +0000
+++ TinyURL.pm  2020-11-12 03:44:06.265375529 +0000
@@ -16,7 +16,7 @@

     # terrible, bad!  skip live testing for now.
     if ( $ENV{'WWW-SHORTEN-TESTING'} ) {
-        return 'http://tinyurl.com/abc12345'
+        return 'https://tinyurl.com/abc12345'
             if ( $url eq 'https://metacpan.org/release/WWW-Shorten' );
         $_error_message = 'Incorrect URL for testing purposes';
         return undef;
@@ -24,7 +24,7 @@

     # back to normality.
     my $ua      = __PACKAGE__->ua();
-    my $tinyurl = 'http://tinyurl.com/api-create.php';
+    my $tinyurl = 'https://tinyurl.com/api-create.php';
     my $resp
         = $ua->post($tinyurl, [url => $url, source => "PerlAPI-$VERSION",]);
     return undef unless $resp->is_success;
@@ -42,7 +42,7 @@
         }
         return undef;
     }
-    if ($resp->content =~ m!(\Qhttp://tinyurl.com/\E\w+)!x) {
+    if ($resp->content =~ m!(\Qhttps://tinyurl.com/\E\w+)!x) {
         return $1;
     }
     return;

**Comment by dsdavis** [comment]
@lembark do you know how to fix this?  Can I simply edit the "TinyURL.pm" file?  If so, do I need to recompile or anything?

I have been using this module for years--but only once a year for a work related purpose (to shorten hundreds of URLs)--and it worked a year ago, and now is broken.

[UPDATE] I was able to fix it, myself.  I simply located the WWW/Shorten/TinyURL.pm file, then searched for "http" and any occurrence that was a tinyurl.com link (and not in a comment, as there were multiple comments with the URL), then change it to https.  I then ran my program, and it worked just fine.  Whew!

[UPDATE 2] Thanks, @lembark for posting about this issue.  I had no idea what was wrong until I saw your Issue post.

**Comment by davorg** [comment]
It looks like this work had already been done even before this issue was raised. But the new version hadn't been released. I'll do that now.

**Comment by dsdavis** [comment]
Thank you, @davorg !!!

**Comment by davorg** [comment]
Ah. Now I remember what happened. I merged the PR with the changes. But when I went to do the release, I noticed that it had changed to using Distzilla. Which scares me.

I'll spend ten minutes seeing if I can make it work. If not, someone cleverer than me will need to do it.

**Comment by davorg** [comment]
(For info, this is fixed in 44501374b5935ec6ad30267b1ce8cedfa9d59b82)

**Comment by davorg** [comment]
Nope. I am in a maze of twisty little Dzil plugins, all alike :-(

**Comment by genio** [comment]
I can jump in on this later this evening. I think @manwar was taking these on though. I don't want to step on toes

**Comment by genio** [comment]
https://metacpan.org/release/CAPOEIRAB/WWW-Shorten-3.094 Should be updated in the wild now.  Thanks everyone!
